#pragma once
// Generated by tools/event_ids.py -- do not edit.
//
// Every RWS message name in SLES_551.47, recovered from the one call
// that gives each CEventId global its name (FUN_001FE780). The comment
// on each line is the address of that global in the retail binary, so a
// name here can be traced back to the decompiled code that sends it.
//
// These are the only message names the game has. A name that is not in
// this list is one we invented, and nothing in the original will answer
// to it.

namespace SHO {
namespace Core {
namespace Events {

// -- Audio ---------------------------------------------------------------
constexpr const char* AudioFreezeSFX                    = "AudioFreezeSFX";  // 0x006b4848
constexpr const char* AudioPauseMusic                   = "AudioPauseMusic";  // 0x006b4828
constexpr const char* AudioPauseSFX                     = "AudioPauseSFX";  // 0x006b4838
constexpr const char* AudioStopAllSFX                   = "AudioStopAllSFX";  // 0x006b4858
constexpr const char* AudioUnfreezeSFX                  = "AudioUnfreezeSFX";  // 0x006b4850
constexpr const char* AudioUnpauseMusic                 = "AudioUnpauseMusic";  // 0x006b4830
constexpr const char* AudioUnpauseSFX                   = "AudioUnpauseSFX";  // 0x006b4840
constexpr const char* AudioVoicesDestroyed              = "AudioVoicesDestroyed";  // 0x006b4818
constexpr const char* AudioVoicesRecreated              = "AudioVoicesRecreated";  // 0x006b4820

// -- Cameras -------------------------------------------------------------
constexpr const char* CamMsgGetFrame                    = "CamMsgGetFrame";  // 0x006b49d0
constexpr const char* CamMsgReceiveTrackingDetails      = "CamMsgReceiveTrackingDetails";  // 0x006b49c8
constexpr const char* CamMsgShakeCamera                 = "CamMsgShakeCamera";  // 0x006b4a10
constexpr const char* CamMsgTnfEnd                      = "CamMsgTnfEnd";  // 0x006b4a08
constexpr const char* CamMsgTnfSetAngle                 = "CamMsgTnfSetAngle";  // 0x006b49f0
constexpr const char* CamMsgTnfSetBias                  = "CamMsgTnfSetBias";  // 0x006b49f8
constexpr const char* CamMsgTnfSetZoom                  = "CamMsgTnfSetZoom";  // 0x006b49e8
constexpr const char* CamMsgTnfStart                    = "CamMsgTnfStart";  // 0x006b4a00

// -- Cheats --------------------------------------------------------------
constexpr const char* CheatMsg_CompleteGame             = "CheatMsg_CompleteGame";  // 0x006bfe28
constexpr const char* CheatMsg_DoubleSpeed              = "CheatMsg_DoubleSpeed";  // 0x006bfdf8
constexpr const char* CheatMsg_EnemyPoison              = "CheatMsg_EnemyPoison";  // 0x006bfe08
constexpr const char* CheatMsg_Invincibility            = "CheatMsg_Invincibility";  // 0x006bfdf0
constexpr const char* CheatMsg_OneHitKill               = "CheatMsg_OneHitKill";  // 0x006bfde8
constexpr const char* CheatMsg_PlayerSuicide            = "CheatMsg_PlayerSuicide";  // 0x006bfe10
constexpr const char* CheatMsg_ReplenishHealth          = "CheatMsg_ReplenishHealth";  // 0x006bfe00
constexpr const char* CheatMsg_TurboMode                = "CheatMsg_TurboMode";  // 0x006bfe18
constexpr const char* CheatMsg_UnlockAll                = "CheatMsg_UnlockAll";  // 0x006bfe20
constexpr const char* CheatMsg_UnlockMap                = "CheatMsg_UnlockMap";  // 0x006bfe30

// -- FMA (grapple / struggle) --------------------------------------------
constexpr const char* FMARespotPlayer                   = "FMARespotPlayer";  // 0x006bfe50
constexpr const char* FMASetState                       = "FMASetState";  // 0x006bfe48

// -- Frame and system ticks ----------------------------------------------
constexpr const char* iMsgAudioGroupDisableGroup        = "iMsgAudioGroupDisableGroup";  // 0x006f8620
constexpr const char* iMsgAudioGroupEnableGroup         = "iMsgAudioGroupEnableGroup";  // 0x006f8628
constexpr const char* iMsgAudioGroupFadeDownGroup       = "iMsgAudioGroupFadeDownGroup";  // 0x006f8610
constexpr const char* iMsgAudioGroupFadeUpGroup         = "iMsgAudioGroupFadeUpGroup";  // 0x006f8618
constexpr const char* iMsgDeleteEntity                  = "iMsgDeleteEntity";  // 0x00701f80
constexpr const char* iMsgDeleteEventHandler            = "iMsgDeleteEventHandler";  // 0x00701f78
constexpr const char* iMsgDoRender                      = "iMsgDoRender";  // 0x006f8e78
constexpr const char* iMsgDoRenderDirectorsCamera       = "iMsgDoRenderDirectorsCamera";  // 0x006f8e80
constexpr const char* iMsgFrameEnd                      = "iMsgFrameEnd";  // 0x006f8e08
constexpr const char* iMsgFrameStart                    = "iMsgFrameStart";  // 0x006f8e00
constexpr const char* iMsgOnDeleteEntity                = "iMsgOnDeleteEntity";  // 0x00701f88
constexpr const char* iMsgPausedPostTick                = "iMsgPausedPostTick";  // 0x006f8da0
constexpr const char* iMsgPausedPreTick                 = "iMsgPausedPreTick";  // 0x006f8d90
constexpr const char* iMsgPausedTick                    = "iMsgPausedTick";  // 0x006f8d98
constexpr const char* iMsgPreShowRaster                 = "iMsgPreShowRaster";  // 0x006f8e98
constexpr const char* iMsgRenderPrepared                = "iMsgRenderPrepared";  // 0x006f8e18
constexpr const char* iMsgRenderScene                   = "iMsgRenderScene";  // 0x006f8e10
constexpr const char* iMsgRunningPostTick               = "iMsgRunningPostTick";  // 0x006f8d88
constexpr const char* iMsgRunningPreTick                = "iMsgRunningPreTick";  // 0x006f8d78
constexpr const char* iMsgRunningTick                   = "iMsgRunningTick";  // 0x006f8d80
constexpr const char* iMsgSetFrozenMode                 = "iMsgSetFrozenMode";  // 0x006f8d70
constexpr const char* iMsgSetPausedMode                 = "iMsgSetPausedMode";  // 0x006f8d68
constexpr const char* iMsgSetRunningMode                = "iMsgSetRunningMode";  // 0x006f8d60
constexpr const char* iMsgStartSystem                   = "iMsgStartSystem";  // 0x006f8df0
constexpr const char* iMsgStopSystem                    = "iMsgStopSystem";  // 0x006f8df8
constexpr const char* iMsgSystemResume                  = "iMsgSystemResume";  // 0x006f8db0
constexpr const char* iMsgSystemStandby                 = "iMsgSystemStandby";  // 0x006f8da8

// -- Front end and HUD ---------------------------------------------------
constexpr const char* MsgUIMapZoomIn                    = "MsgUIMapZoomIn";  // 0x006b4938
constexpr const char* MsgUIMapZoomOut                   = "MsgUIMapZoomOut";  // 0x006b4940
constexpr const char* MsgUIOpenMap                      = "MsgUIOpenMap";  // 0x006b4930
constexpr const char* MsgUiDrinkHealth                  = "MsgUiDrinkHealth";  // 0x006b4970
constexpr const char* MsgUiEquip                        = "MsgUiEquip";  // 0x006b4960
constexpr const char* MsgUiFrontEndLoop                 = "MsgUiFrontEndLoop";  // 0x006b4910
constexpr const char* MsgUiFrontEndLoopIsPlaying        = "MsgUiFrontEndLoopIsPlaying";  // 0x006b4920
constexpr const char* MsgUiFrontEndLoopStop             = "MsgUiFrontEndLoopStop";  // 0x006b4918
constexpr const char* MsgUiGenericSwap                  = "MsgUiGenericSwap";  // 0x006b4900
constexpr const char* MsgUiHUDSwap                      = "MsgUiHUDSwap";  // 0x006b48e8
constexpr const char* MsgUiHUDSwapFail                  = "MsgUiHUDSwapFail";  // 0x006b48f0
constexpr const char* MsgUiItemPickup                   = "MsgUiItemPickup";  // 0x006b4988
constexpr const char* MsgUiKonamiCode                   = "MsgUiKonamiCode";  // 0x006b4990
constexpr const char* MsgUiLevelCommence                = "MsgUiLevelCommence";  // 0x006b4908
constexpr const char* MsgUiMusicSlider                  = "MsgUiMusicSlider";  // 0x006b48d8
constexpr const char* MsgUiNavigateDown                 = "MsgUiNavigateDown";  // 0x006b4898
constexpr const char* MsgUiNavigateLeft                 = "MsgUiNavigateLeft";  // 0x006b48a0
constexpr const char* MsgUiNavigateRight                = "MsgUiNavigateRight";  // 0x006b48a8
constexpr const char* MsgUiNavigateUp                   = "MsgUiNavigateUp";  // 0x006b4890
constexpr const char* MsgUiNavigationEnd                = "MsgUiNavigationEnd";  // 0x006b48b0
constexpr const char* MsgUiRadioOff                     = "MsgUiRadioOff";  // 0x006b4950
constexpr const char* MsgUiRadioOn                      = "MsgUiRadioOn";  // 0x006b4948
constexpr const char* MsgUiReload                       = "MsgUiReload";  // 0x006b4968
constexpr const char* MsgUiSaveGame                     = "MsgUiSaveGame";  // 0x006b4928
constexpr const char* MsgUiSelectCancel                 = "MsgUiSelectCancel";  // 0x006b48c8
constexpr const char* MsgUiSelectFail                   = "MsgUiSelectFail";  // 0x006b48c0
constexpr const char* MsgUiSelectOk                     = "MsgUiSelectOk";  // 0x006b48b8
constexpr const char* MsgUiSlider                       = "MsgUiSlider";  // 0x006b48d0
constexpr const char* MsgUiToggle                       = "MsgUiToggle";  // 0x006b48e0
constexpr const char* MsgUiTorchOff                     = "MsgUiTorchOff";  // 0x006b4980
constexpr const char* MsgUiTorchOn                      = "MsgUiTorchOn";  // 0x006b4978
constexpr const char* MsgUiTransition                   = "MsgUiTransition";  // 0x006b48f8
constexpr const char* MsgUiUnequip                      = "MsgUiUnequip";  // 0x006b4958

// -- Gameplay commands ---------------------------------------------------
constexpr const char* MsgActivate                       = "MsgActivate";  // 0x006f8bb8
constexpr const char* MsgDeactivate                     = "MsgDeactivate";  // 0x006f8bc0
constexpr const char* MsgDecreaseMasterVolume           = "MsgDecreaseMasterVolume";  // 0x006bfef0
constexpr const char* MsgDecreaseMusicVolume            = "MsgDecreaseMusicVolume";  // 0x006bff00
constexpr const char* MsgDecreaseSfxVolume              = "MsgDecreaseSfxVolume";  // 0x006bff10
constexpr const char* MsgDiableHUD                      = "MsgDiableHUD";  // 0x006bf550
constexpr const char* MsgEnableTimerHUD                 = "MsgEnableTimerHUD";  // 0x006bf520
constexpr const char* MsgGetPadButtonMask               = "MsgGetPadButtonMask";  // 0x006cc2a8
constexpr const char* MsgGiveInitialEquip               = "MsgGiveInitialEquip";  // 0x006cc290
constexpr const char* MsgGrabCancel                     = "MsgGrabCancel";  // 0x006b4b10
constexpr const char* MsgGrabFinished                   = "MsgGrabFinished";  // 0x006b4b08
constexpr const char* MsgGrabStarted                    = "MsgGrabStarted";  // 0x006b4b00
constexpr const char* MsgIncreaseMasterVolume           = "MsgIncreaseMasterVolume";  // 0x006bfee8
constexpr const char* MsgIncreaseMusicVolume            = "MsgIncreaseMusicVolume";  // 0x006bfef8
constexpr const char* MsgIncreaseSfxVolume              = "MsgIncreaseSfxVolume";  // 0x006bff08
constexpr const char* MsgItemEquipped                   = "MsgItemEquipped";  // 0x006cc280
constexpr const char* MsgLoadGameData                   = "MsgLoadGameData";  // 0x006f8bd0
constexpr const char* MsgPlayTransition                 = "MsgPlayTransition";  // 0x006b4870
constexpr const char* MsgRelocateAllEnemies             = "MsgRelocateAllEnemies";  // 0x006f8688
constexpr const char* MsgResumeRumble                   = "MsgResumeRumble";  // 0x006cc2e8
constexpr const char* MsgSaveGameData                   = "MsgSaveGameData";  // 0x006f8bc8
constexpr const char* MsgSetAllEnemiesAware             = "MsgSetAllEnemiesAware";  // 0x006f8680
constexpr const char* MsgSetGrabSyncState               = "MsgSetGrabSyncState";  // 0x006b4b18
constexpr const char* MsgStartBigRumble                 = "MsgStartBigRumble";  // 0x006cc2b8
constexpr const char* MsgStartFiremanTimer              = "MsgStartFiremanTimer";  // 0x006bff18
constexpr const char* MsgStartSmallRumble               = "MsgStartSmallRumble";  // 0x006cc2c0
constexpr const char* MsgStopAllRumble                  = "MsgStopAllRumble";  // 0x006cc2d8
constexpr const char* MsgStopBigRumble                  = "MsgStopBigRumble";  // 0x006cc2c8
constexpr const char* MsgStopFiremanTimer               = "MsgStopFiremanTimer";  // 0x006bff20
constexpr const char* MsgStopSmallRumble                = "MsgStopSmallRumble";  // 0x006cc2d0
constexpr const char* MsgStopSubtitles                  = "MsgStopSubtitles";  // 0x006cc1d8
constexpr const char* MsgSubtitlesPause                 = "MsgSubtitlesPause";  // 0x006cc1c8
constexpr const char* MsgSubtitlesResume                = "MsgSubtitlesResume";  // 0x006cc1d0
constexpr const char* MsgSuspendRumble                  = "MsgSuspendRumble";  // 0x006cc2e0
constexpr const char* MsgWeaponBroken                   = "MsgWeaponBroken";  // 0x006cc288

// -- Ghost Rider leftovers -- unused by Origins --------------------------
constexpr const char* TutorialBeenHit                   = "TutorialBeenHit";  // 0x006b4b20
constexpr const char* TutorialComboLevel1               = "TutorialComboLevel1";  // 0x006b4b28
constexpr const char* TutorialEnemyDazed                = "TutorialEnemyDazed";  // 0x006b4b58
constexpr const char* TutorialHasGrabbed                = "TutorialHasGrabbed";  // 0x006b4b50
constexpr const char* TutorialLinkGaugeFull             = "TutorialLinkGaugeFull";  // 0x006b4b48
constexpr const char* TutorialLowEssenceReached         = "TutorialLowEssenceReached";  // 0x006b4b40
constexpr const char* TutorialPenanceGaugeHalf          = "TutorialPenanceGaugeHalf";  // 0x006b4b38
constexpr const char* TutorialPickedUpEssence           = "TutorialPickedUpEssence";  // 0x006b4b30

// -- In-game cutscenes ---------------------------------------------------
constexpr const char* IGCActive                         = "IGCActive";  // 0x006cc210
constexpr const char* IGCEnd                            = "IGCEnd";  // 0x006cc1f8
constexpr const char* IGCSkip                           = "IGCSkip";  // 0x006cc200
constexpr const char* IGCSkipRequest                    = "IGCSkipRequest";  // 0x006cc208
constexpr const char* IGCStart                          = "IGCStart";  // 0x006cc1f0

// -- Other ---------------------------------------------------------------
constexpr const char* CheckpointActivated               = "CheckpointActivated";  // 0x006bf3b0
constexpr const char* DisablePlayerCombat               = "DisablePlayerCombat";  // 0x006b4bb8
constexpr const char* EnablePlayerCombat                = "EnablePlayerCombat";  // 0x006b4bb0
constexpr const char* EnablePlayerControl               = "EnablePlayerControl";  // 0x006b4bc8
constexpr const char* EnablePlayerRender                = "EnablePlayerRender";  // 0x006b4bc0
constexpr const char* Ended                             = "Ended";  // 0x006bff68
constexpr const char* FindPlayerCheckpoint              = "FindPlayerCheckpoint";  // 0x006bf3a0
constexpr const char* FindPlayerSpawners                = "FindPlayerSpawners";  // 0x006bf3d0
constexpr const char* GetPlayer                         = "GetPlayer";  // 0x006b4ae0
constexpr const char* GetPlayerAttackAnim               = "GetPlayerAttackAnim";  // 0x006b4be8
constexpr const char* KillPlayerWithExplosion           = "KillPlayerWithExplosion";  // 0x006b4bf0
constexpr const char* MSG_GIsBorderEnabled              = "MSG_GIsBorderEnabled";  // 0x006bf4e8
constexpr const char* MSG_GKillFMABorder                = "MSG_GKillFMABorder";  // 0x006bf4f0
constexpr const char* OnRegisterDeleteEntity            = "OnRegisterDeleteEntity";  // 0x00701f90
constexpr const char* OneShotDestroyed                  = "OneShotDestroyed";  // 0x006b4c40
constexpr const char* PauseEnemies                      = "PauseEnemies";  // 0x006b4af8
constexpr const char* PlayZoneCue                       = "PlayZoneCue";  // 0x006b47d8
constexpr const char* PublishPlayerSpawner              = "PublishPlayerSpawner";  // 0x006bf3d8
constexpr const char* RePlayZoneCue                     = "RePlayZoneCue";  // 0x006b47d0
constexpr const char* RespawnPlayer                     = "RespawnPlayer";  // 0x006bf3e0
constexpr const char* RespotPlayer                      = "RespotPlayer";  // 0x006bf3a8
constexpr const char* SFXManagerInitializedMsg          = "SFXManagerInitializedMsg";  // 0x006bfae0
constexpr const char* SetZoneCueVolume                  = "SetZoneCueVolume";  // 0x006b47e8
constexpr const char* StartFireRain                     = "StartFireRain";  // 0x006bf5c0
constexpr const char* StopFireRain                      = "StopFireRain";  // 0x006bf5c8
constexpr const char* StopZoneCue                       = "StopZoneCue";  // 0x006b47e0
constexpr const char* Update                            = "Update";  // 0x00703210
constexpr const char* boss_trigger                      = "boss_trigger";  // 0x006bfc48
constexpr const char* enemy_trigger                     = "enemy_trigger";  // 0x006bfc40
constexpr const char* msgEnableFMABorder                = "msgEnableFMABorder";  // 0x006b4a48
constexpr const char* player_trigger                    = "player_trigger";  // 0x006bfc38
constexpr const char* race_start_line_trigger           = "race_start_line_trigger";  // 0x006bfc50

// -- Player --------------------------------------------------------------
constexpr const char* PlayerActivate                    = "PlayerActivate";  // 0x006b4ba0
constexpr const char* PlayerDeactivate                  = "PlayerDeactivate";  // 0x006b4ba8
constexpr const char* PlayerHeartBeat1                  = "PlayerHeartBeat1";  // 0x006b4c10
constexpr const char* PlayerHeartBeat2                  = "PlayerHeartBeat2";  // 0x006b4c18
constexpr const char* PlayerSwitchedWeaponLeft          = "PlayerSwitchedWeaponLeft";  // 0x006b4bd0
constexpr const char* PlayerSwitchedWeaponRight         = "PlayerSwitchedWeaponRight";  // 0x006b4bd8
constexpr const char* PlayerSwitchedWeaponType          = "PlayerSwitchedWeaponType";  // 0x006b4be0
constexpr const char* PlayerTorchCreated                = "PlayerTorchCreated";  // 0x006b4c08
constexpr const char* PlayerTorchOff                    = "PlayerTorchOff";  // 0x006b4c00
constexpr const char* PlayerTorchOn                     = "PlayerTorchOn";  // 0x006b4bf8

// -- Projectile weapons --------------------------------------------------
constexpr const char* PWMsgProjectileFire               = "PWMsgProjectileFire";  // 0x006bf4c0
constexpr const char* PWMsgProjectileKill               = "PWMsgProjectileKill";  // 0x006bf4c8
constexpr const char* PWMsgReceiveFireEvent             = "PWMsgReceiveFireEvent";  // 0x006bf4b8

// -- Radio and screen static ---------------------------------------------
constexpr const char* RadioStaticDisable                = "RadioStaticDisable";  // 0x006b4c28
constexpr const char* RadioStaticEnable                 = "RadioStaticEnable";  // 0x006b4c20
constexpr const char* ScreenStaticDisable               = "ScreenStaticDisable";  // 0x006b4c38
constexpr const char* ScreenStaticEnable                = "ScreenStaticEnable";  // 0x006b4c30

// -- Reflections and awareness -------------------------------------------
constexpr const char* Characters__MsgPingAwareness      = "Characters::MsgPingAwareness";  // 0x006b4b68
constexpr const char* Characters__MsgReflectAddClump    = "Characters::MsgReflectAddClump";  // 0x006b4c68
constexpr const char* Characters__MsgReflectDelClump    = "Characters::MsgReflectDelClump";  // 0x006b4c70
constexpr const char* Characters__MsgReflectDisableClump = "Characters::MsgReflectDisableClump";  // 0x006b4c80
constexpr const char* Characters__MsgReflectEnableClump = "Characters::MsgReflectEnableClump";  // 0x006b4c78
constexpr const char* Characters__MsgReflectReposClump  = "Characters::MsgReflectReposClump";  // 0x006b4c88
constexpr const char* Characters__MsgReflectReposTorch  = "Characters::MsgReflectReposTorch";  // 0x006b4c90
constexpr const char* Characters__ReflectionDisable     = "Characters::ReflectionDisable";  // 0x006b4c58
constexpr const char* Characters__ReflectionEnable      = "Characters::ReflectionEnable";  // 0x006b4c60

// -- Zones ---------------------------------------------------------------
constexpr const char* ZoneActivate                      = "ZoneActivate";  // 0x006bfd80
constexpr const char* ZoneDeactivate                    = "ZoneDeactivate";  // 0x006bfd88
constexpr const char* ZoneLoadTransitions               = "ZoneLoadTransitions";  // 0x006bfdb0
constexpr const char* ZonePreCache                      = "ZonePreCache";  // 0x006bfd98
constexpr const char* ZoneReset                         = "ZoneReset";  // 0x006bfd90
constexpr const char* ZoneRespotAll                     = "ZoneRespotAll";  // 0x006bfdc8
constexpr const char* ZoneRespotVector                  = "ZoneRespotVector";  // 0x006bfdd0
constexpr const char* ZoneSpawnsDumping                 = "ZoneSpawnsDumping";  // 0x006bfda8
constexpr const char* ZoneTransitionBegin               = "ZoneTransitionBegin";  // 0x006bfdb8
constexpr const char* ZoneTransitionEnd                 = "ZoneTransitionEnd";  // 0x006bfdc0
constexpr const char* ZoneUnCache                       = "ZoneUnCache";  // 0x006bfda0

constexpr int kCount = 206;

} // namespace Events
} // namespace Core
} // namespace SHO
