"""Recover the RWS event-name table out of the Origins PS2 executable.

Every `RWS::CEventId` in the game is a global that is given its name by one
call, `FUN_001FE780(&id, "Name", subname)` -- the interning routine that hashes
the string into the global id table (Ghost Rider's
`RWS::CEventHandler::RegisterMsg` reaches it through the same path).  There is
no name anywhere in the id itself, so the only way to learn what a `DAT_006B4xxx`
means is to find its one registration site.

The decompiled tree makes that a text search: scan `decomp/sles_r5900/` for the
call, take the two address literals, and resolve the second through the ELF.

Writes docs/generated/sho_event_ids.json:  {"0x6b4bf8": "PlayerTorchOn", ...}
and SHO-port/include/SHO/Core/EventIds.h, so port code names a message the way
the game names it instead of inventing one.

    python3 tools/event_ids.py
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sles import Sles

DECOMP = 'decomp/sles_r5900'
ELF = 'game-iso/SHO/SLES_551.47'
OUT = 'docs/generated/sho_event_ids.json'
HEADER = 'SHO-port/include/SHO/Core/EventIds.h'

# The prefix each name is filed under in the generated header. Longest match
# wins, so "MsgUi" beats "Msg".
GROUPS = [
    ('iMsg', 'Frame and system ticks'),
    ('MsgUi', 'Front end and HUD'),
    ('MsgUI', 'Front end and HUD'),
    ('Msg', 'Gameplay commands'),
    ('Player', 'Player'),
    ('Cheat', 'Cheats'),
    ('Cam', 'Cameras'),
    ('Zone', 'Zones'),
    ('Audio', 'Audio'),
    ('Tutorial', 'Ghost Rider leftovers -- unused by Origins'),
    ('IGC', 'In-game cutscenes'),
    ('FMA', 'FMA (grapple / struggle)'),
    ('PW', 'Projectile weapons'),
    ('Characters::', 'Reflections and awareness'),
    ('Radio', 'Radio and screen static'),
    ('Screen', 'Radio and screen static'),
]


def cident(name):
    """A C++ identifier for a message name."""
    return re.sub(r'[^A-Za-z0-9]', '_', name)


def group_of(name):
    best = ''
    label = 'Other'
    for prefix, lbl in GROUPS:
        if name.startswith(prefix) and len(prefix) > len(best):
            best, label = prefix, lbl
    return label


def write_header(ids):
    by_group = {}
    for addr, name in sorted(ids.items(), key=lambda kv: kv[1]):
        by_group.setdefault(group_of(name), []).append((addr, name))

    lines = [
        '#pragma once',
        '// Generated by tools/event_ids.py -- do not edit.',
        '//',
        '// Every RWS message name in SLES_551.47, recovered from the one call',
        '// that gives each CEventId global its name (FUN_001FE780). The comment',
        '// on each line is the address of that global in the retail binary, so a',
        '// name here can be traced back to the decompiled code that sends it.',
        '//',
        '// These are the only message names the game has. A name that is not in',
        '// this list is one we invented, and nothing in the original will answer',
        '// to it.',
        '',
        'namespace SHO {',
        'namespace Core {',
        'namespace Events {',
        '',
    ]
    for label in sorted(by_group):
        lines.append(f'// -- {label} ' + '-' * max(0, 68 - len(label)))
        for addr, name in by_group[label]:
            ident = cident(name)
            pad = ' ' * max(1, 34 - len(ident))
            lines.append(f'constexpr const char* {ident}{pad}= "{name}";'
                         f'  // 0x{addr:08x}')
        lines.append('')
    lines += [
        f'constexpr int kCount = {len(ids)};',
        '',
        '} // namespace Events',
        '} // namespace Core',
        '} // namespace SHO',
        '',
    ]
    os.makedirs(os.path.dirname(HEADER), exist_ok=True)
    with open(HEADER, 'w') as f:
        f.write('\n'.join(lines))
    print(f'{len(ids)} names -> {HEADER}')

# FUN_001FE780(CEventId *id, const char *name, const char *subname)
REGISTER = re.compile(
    r'FUN_001fe780\(\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*,')


def main():
    s = Sles(ELF)
    ids = {}
    clashes = []
    for fn in sorted(os.listdir(DECOMP)):
        if not fn.endswith('.c'):
            continue
        text = open(os.path.join(DECOMP, fn), errors='ignore').read()
        for m in REGISTER.finditer(text):
            ev = int(m.group(1), 16)
            name = s.string(int(m.group(2), 16), 64)
            if name is None:
                continue
            if ids.get(ev, name) != name:
                clashes.append((ev, ids[ev], name, fn))
            ids[ev] = name

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        json.dump({f'0x{k:x}': v for k, v in sorted(ids.items())}, f, indent=1)
        f.write('\n')
    print(f'{len(ids)} event ids -> {OUT}')
    for c in clashes:
        print(f'  clash 0x{c[0]:x}: {c[1]!r} vs {c[2]!r} in {c[3]}')
    write_header(ids)


if __name__ == '__main__':
    main()
